[log]
LogPath = ""
LogLevel = "debug"
MaxSize = 10
Compress = true
MaxAge = 7
MaxBackups = 10
Format = "json"

[redis]
Network = "tcp"
Addr = "10.101.191.106:6379"
DB = 13
DialTimeout = 1000
ReadTimeout = 1000
WriteTimeout = 3000
PoolSize = 1024
PoolTimeout = 300

[mongo]
Host = "10.101.191.106:27017"
Database = "SecurityManagement"
Mode = "Strong"
DialTimeout = 1
ReadTimeout = 3
WriteTimeout = 5
PoolSize = 4096
PoolTimeout = 300
SyncTimeout = 5
SafeWriteAck = 1
SafeWriteTimeout = 5000
SafeJournal = false
[mongo.auth]
User = "admin"
Passwd = "123456"
Database = "admin"

[consumer]
Port = 9090
Mode = "debug"
MaxWorkers = 10
MaxQueue = 10
TimeOut = 3
GrpcPort = 9092

[producer]
Port = 9091
Mode = "debug"
WorkChatUploadUrl = "https://qyapi.weixin.qq.com/cgi-bin/webhook/upload_media?key=Your-Key&type=file"
WorkChatBotUrl = "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=Your-Key"
GrpcPort = 9092