name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Remove unused dependencies
        run: go mod tidy

      - name: Install dependencies
        run: |
          go version
          go get -u .

      - name: Run build
        run: go build .

      - name: Run testing
        run: go test `go list ./... | grep -v dao | grep -v consul `